"""
infrastructure/mapper.py — Maps raw detector outputs to domain objects.

Also provides camera ID parsing utilities used by the API layer.

Responsibility: translate model-specific dicts/tensors into domain
Detection objects so the domain never sees raw class IDs or pixel coords.

Note: `risk` is NOT computed here. Risk calculation is a domain concern
handled by RiskEngine in the application layer after mapping.
"""

from __future__ import annotations

import uuid

from app.core.logging import get_logger
from app.modules.vision.domain.entities import Detection
from app.modules.vision.domain.enums import HazardType
from app.modules.vision.domain.value_objects import BoundingBox

log = get_logger("vision.mapper")


def parse_camera_id(camera_id: str) -> uuid.UUID:
    """
    Parse a camera ID string into a UUID.

    If the string is already a valid UUID, it is returned as-is.
    Otherwise a deterministic UUID v5 is derived from the string so that
    the same camera label always maps to the same UUID.
    """
    try:
        return uuid.UUID(camera_id)
    except ValueError:
        return uuid.uuid5(uuid.NAMESPACE_DNS, camera_id)


# ── Class-name → HazardType mapping ──────────────────────────────────────────
# Add new detector class labels here without touching any other file.

_CLASS_TO_HAZARD: dict[str, HazardType] = {
    # YOLO safety dataset (common labels)
    "person":              HazardType.PERSON,
    "helmet":              HazardType.HELMET,
    "hardhat":             HazardType.HELMET,
    "no-helmet":           HazardType.NO_HELMET,
    "no_helmet":           HazardType.NO_HELMET,
    "no-hardhat":          HazardType.NO_HELMET,
    "vest":                HazardType.SAFETY_VEST,
    "safety-vest":         HazardType.SAFETY_VEST,
    "safety_vest":         HazardType.SAFETY_VEST,
    "no-vest":             HazardType.NO_SAFETY_VEST,
    "no_vest":             HazardType.NO_SAFETY_VEST,
    "no-safety-vest":      HazardType.NO_SAFETY_VEST,
    "no_safety_vest":      HazardType.NO_SAFETY_VEST,
    "fire":                HazardType.FIRE,
    "smoke":               HazardType.SMOKE,
    "chemical-spill":      HazardType.CHEMICAL_SPILL,
    "chemical_spill":      HazardType.CHEMICAL_SPILL,
    "fall":                HazardType.FALL,
    "falling":             HazardType.FALL,
    "machinery":           HazardType.MACHINERY,
    "machine":             HazardType.MACHINERY,
    "forklift":            HazardType.MACHINERY,
    "crane":               HazardType.MACHINERY,
    # Unknown / unclassified
    "unknown":             HazardType.UNKNOWN,
}


def map_raw_detection(
    raw: dict,
    frame_id: str,
    camera_id: str,
    image_path: str | None = None,
) -> Detection | None:
    """
    Convert a single raw detector output dict to a domain Detection.

    Expected keys in `raw`:
        class_name, confidence, x1, y1, x2, y2, image_width, image_height

    Returns None only if the bounding box cannot be constructed.
    Unknown class names map to HazardType.UNKNOWN (never return None for that).
    """
    class_name  = raw.get("class_name", "").lower().strip()
    hazard_type = _CLASS_TO_HAZARD.get(class_name)

    if hazard_type is None:
        log.warning(
            f"Unknown class label '{class_name}' — mapped to UNKNOWN. "
            f"Add it to infrastructure/mapper.py for a precise category."
        )
        hazard_type = HazardType.UNKNOWN

    try:
        bounding_box = BoundingBox.from_xyxy_pixels(
            x_min=int(raw["x1"]),
            y_min=int(raw["y1"]),
            x_max=int(raw["x2"]),
            y_max=int(raw["y2"]),
            image_width=int(raw["image_width"]),
            image_height=int(raw["image_height"]),
        )
    except (KeyError, ValueError, ZeroDivisionError) as exc:
        log.warning(f"Bounding box construction failed for '{class_name}': {exc}")
        return None

    confidence = float(raw["confidence"])

    return Detection(
        hazard_type=hazard_type,
        confidence=confidence,
        bounding_box=bounding_box,
        frame_id=frame_id,
        camera_id=camera_id,
        # id, status, detected_at are auto-generated by the entity
    )


def map_raw_detections(
    raws: list[dict],
    frame_id: str,
    camera_id: str,
    image_path: str | None = None,
    min_confidence: float = 0.0,
) -> list[Detection]:
    """
    Convert a list of raw detector output dicts to domain Detections.

    Detections below `min_confidence` are skipped before mapping.
    """
    results: list[Detection] = []

    for raw in raws:
        if float(raw.get("confidence", 0.0)) < min_confidence:
            continue

        det = map_raw_detection(raw, frame_id, camera_id, image_path)
        if det is not None:
            results.append(det)

    log.debug(
        f"Mapped {len(results)}/{len(raws)} raw detections "
        f"(threshold={min_confidence})"
    )
    return results
