from __future__ import annotations
from abc import ABC, abstractmethod
from app.modules.vision.domain.entities.vision_alert import VisionAlert

class AlertRepository(ABC):
    @abstractmethod
    async def save_alert(self, alert: VisionAlert) -> VisionAlert: ...
    @abstractmethod
    async def get_alert(self, alert_id: str) -> VisionAlert | None: ...
    @abstractmethod
    async def update_alert(self, alert: VisionAlert) -> VisionAlert: ...
    @abstractmethod
    async def list_alerts(self, zone_id: str | None = None, severity: str | None = None, status: str | None = None, camera_id: str | None = None, limit: int = 100, offset: int = 0) -> list[VisionAlert]: ...
    @abstractmethod
    async def count_active_alerts(self, zone_id: str | None = None) -> int: ...
