from __future__ import annotations
from abc import ABC, abstractmethod
from datetime import datetime
from app.modules.vision.domain.entities.frame import Frame
from app.modules.vision.domain.entities.frame_metadata import FrameMetadata

class FrameRepository(ABC):
    @abstractmethod
    async def save_frame(self, frame: Frame) -> Frame: ...
    @abstractmethod
    async def get_frame(self, frame_id: str) -> Frame | None: ...
    @abstractmethod
    async def save_metadata(self, metadata: FrameMetadata) -> FrameMetadata: ...
    @abstractmethod
    async def get_metadata(self, frame_id: str) -> FrameMetadata | None: ...
    @abstractmethod
    async def list_frames_by_camera(self, camera_id: str, limit: int = 50, offset: int = 0) -> list[Frame]: ...
    @abstractmethod
    async def list_frames_in_window(self, camera_id: str, start: datetime, end: datetime) -> list[Frame]: ...
    @abstractmethod
    async def delete_old_frames(self, camera_id: str, before: datetime) -> int: ...
