from __future__ import annotations
from abc import ABC, abstractmethod
from app.modules.vision.domain.entities.tracking_object import TrackingObject
from app.modules.vision.domain.entities.tracking_history import TrackingHistory

class TrackingRepository(ABC):
    @abstractmethod
    async def save_track(self, track: TrackingObject) -> TrackingObject: ...
    @abstractmethod
    async def get_track(self, track_id: str) -> TrackingObject | None: ...
    @abstractmethod
    async def update_track(self, track: TrackingObject) -> TrackingObject: ...
    @abstractmethod
    async def list_active_tracks(self, camera_id: str | None = None) -> list[TrackingObject]: ...
    @abstractmethod
    async def list_tracks_by_camera(self, camera_id: str, limit: int = 50, offset: int = 0) -> list[TrackingObject]: ...
    @abstractmethod
    async def end_track(self, track_id: str) -> None: ...
    @abstractmethod
    async def save_history(self, history: TrackingHistory) -> TrackingHistory: ...
    @abstractmethod
    async def get_history(self, track_id: str) -> TrackingHistory | None: ...
