"""
domain/enums/stream_event_type.py — StreamEventType enum.

Canonical vocabulary of all domain events generated by Vision Intelligence.
"""
from enum import Enum


class StreamEventType(str, Enum):
    FRAME_CAPTURED        = "FrameCaptured"
    OBJECT_DETECTED       = "ObjectDetected"
    TRACKING_STARTED      = "TrackingStarted"
    TRACKING_ENDED        = "TrackingEnded"
    RESTRICTED_ZONE_ENTRY = "RestrictedZoneEntry"
    FIRE_DETECTED         = "FireDetected"
    SMOKE_DETECTED        = "SmokeDetected"
    EQUIPMENT_DETECTED    = "EquipmentDetected"
    WORKER_DETECTED       = "WorkerDetected"
    CAMERA_OFFLINE        = "CameraOffline"
    CAMERA_RECOVERED      = "CameraRecovered"
    DETECTION_FAILED      = "DetectionFailed"
    PPE_VIOLATION         = "PPEViolation"
    OCCUPANCY_EXCEEDED    = "OccupancyExceeded"
