"""
domain/enums/vision_safety_enums.py — Enums for Vision Safety Intelligence Engine.
"""
from enum import Enum


class PPEType(str, Enum):
    HELMET = "HELMET"
    SAFETY_VEST = "SAFETY_VEST"
    SAFETY_SHOES = "SAFETY_SHOES"
    GLOVES = "GLOVES"
    MASK = "MASK"
    FACE_SHIELD = "FACE_SHIELD"
    GOGGLES = "GOGGLES"
    HARNESS = "HARNESS"
    EAR_PROTECTION = "EAR_PROTECTION"


class UnsafeBehaviorType(str, Enum):
    RUNNING_IN_HAZARDOUS_ZONE = "RUNNING_IN_HAZARDOUS_ZONE"
    ENTERING_RESTRICTED_AREA = "ENTERING_RESTRICTED_AREA"
    STANDING_UNDER_SUSPENDED_LOAD = "STANDING_UNDER_SUSPENDED_LOAD"
    UNSAFE_LADDER_USAGE = "UNSAFE_LADDER_USAGE"
    IMPROPER_LIFTING_POSTURE = "IMPROPER_LIFTING_POSTURE"
    WORKER_TOO_CLOSE_TO_MACHINERY = "WORKER_TOO_CLOSE_TO_MACHINERY"
    IGNORING_SAFETY_BARRIER = "IGNORING_SAFETY_BARRIER"
    SMOKING_IN_PROHIBITED_AREA = "SMOKING_IN_PROHIBITED_AREA"


class ZoneViolationType(str, Enum):
    UNAUTHORIZED_ENTRY = "UNAUTHORIZED_ENTRY"
    LOITERING = "LOITERING"
    AFTER_HOURS_ACCESS = "AFTER_HOURS_ACCESS"
    CAPACITY_EXCEEDED = "CAPACITY_EXCEEDED"
    ROLE_MISMATCH = "ROLE_MISMATCH"


class EquipmentInteractionType(str, Enum):
    WORKER_NEAR_FORKLIFT = "WORKER_NEAR_FORKLIFT"
    WORKER_NEAR_CRANE = "WORKER_NEAR_CRANE"
    WORKER_INSIDE_ROBOT_CELL = "WORKER_INSIDE_ROBOT_CELL"
    WORKER_NEAR_ROTATING_MACHINERY = "WORKER_NEAR_ROTATING_MACHINERY"
    UNSAFE_EQUIPMENT_PROXIMITY = "UNSAFE_EQUIPMENT_PROXIMITY"


class FallType(str, Enum):
    SUDDEN_DESCENT = "SUDDEN_DESCENT"
    POSTURE_COLLAPSE = "POSTURE_COLLAPSE"
    SLIP_TRIP = "SLIP_TRIP"
    HEIGHT_FALL = "HEIGHT_FALL"


class VerificationStatus(str, Enum):
    UNVERIFIED = "UNVERIFIED"
    PENDING_FUSION = "PENDING_FUSION"
    CONFIRMED = "CONFIRMED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    ESCALATED = "ESCALATED"
