import { Sensor, Alert, Worker, WorkPermit, SystemNotification, User, CopilotMessage } from '../types';

export const MOCK_USER: User = {
  id: 'usr-9428',
  name: 'Devin Vance',
  email: 'd.vance@abhedya.ai',
  role: 'SAFETY_SUPERVISOR',
  plantId: 'PLANT-04-TX',
  permissions: [
    'sensors:read',
    'permits:create',
    'permits:approve',
    'permits:revoke',
    'workers:read',
    'workers:track',
    'emergency:trigger',
    'emergency:clear',
    'system:audit_log',
  ],
  avatarUrl: undefined,
};

// Generates time-series historical values
const generateHistory = (base: number, length = 10, variance = 2) => {
  return Array.from({ length }).map((_, i) => ({
    timestamp: new Date(Date.now() - (10 - i) * 60000).toISOString(),
    value: parseFloat((base + (Math.random() - 0.5) * variance).toFixed(2)),
  }));
};

export const MOCK_SENSORS: Sensor[] = [
  {
    id: 'sns-temp-01',
    name: 'Reactor 02 Core Temp',
    type: 'TEMPERATURE',
    status: 'NORMAL',
    value: 78.4,
    unit: '°C',
    location: 'Sector A - Hydrocracker',
    lastUpdated: new Date().toISOString(),
    minThreshold: 0,
    maxThreshold: 110,
    historicalData: generateHistory(78, 15, 3),
  },
  {
    id: 'sns-pres-02',
    name: 'Crude Feed Line Pressure',
    type: 'PRESSURE',
    status: 'WARNING',
    value: 842.1,
    unit: 'kPa',
    location: 'Sector A - Main Feed Pipe',
    lastUpdated: new Date().toISOString(),
    minThreshold: 100,
    maxThreshold: 800,
    historicalData: generateHistory(795, 15, 20),
  },
  {
    id: 'sns-gas-03',
    name: 'Gas Detector - H2S Point 04',
    type: 'GAS_LEAK',
    status: 'CRITICAL',
    value: 12.8,
    unit: 'ppm',
    location: 'Sector C - Sulfur Recovery',
    lastUpdated: new Date().toISOString(),
    minThreshold: 0,
    maxThreshold: 10,
    historicalData: generateHistory(3, 15, 4),
  },
  {
    id: 'sns-vib-04',
    name: 'Compressor C-104 Bearing Vibration',
    type: 'VIBRATION',
    status: 'NORMAL',
    value: 1.4,
    unit: 'mm/s',
    location: 'Sector B - Compressor Deck',
    lastUpdated: new Date().toISOString(),
    minThreshold: 0,
    maxThreshold: 4.5,
    historicalData: generateHistory(1.3, 15, 0.2),
  },
  {
    id: 'sns-temp-05',
    name: 'Furnace F-101 Exhaust Temp',
    type: 'TEMPERATURE',
    status: 'CRITICAL',
    value: 624.8,
    unit: '°C',
    location: 'Sector B - Primary Furnace',
    lastUpdated: new Date().toISOString(),
    minThreshold: 100,
    maxThreshold: 600,
    historicalData: generateHistory(590, 15, 15),
  },
  {
    id: 'sns-flow-06',
    name: 'Naphtha Output Flow Rate',
    type: 'FLOW_RATE',
    status: 'OFFLINE',
    value: 0,
    unit: 'm³/h',
    location: 'Sector A - Fractionator',
    lastUpdated: new Date(Date.now() - 4500000).toISOString(),
    minThreshold: 5,
    maxThreshold: 80,
    historicalData: [],
  },
];

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alt-1029',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    severity: 'CRITICAL',
    status: 'ACTIVE',
    category: 'SAFETY',
    message: 'Hydrogen Sulfide (H2S) concentration exceeded critical limits (12.8 ppm)',
    location: 'Sector C - Sulfur Recovery Unit',
    sensorId: 'sns-gas-03',
  },
  {
    id: 'alt-1028',
    timestamp: new Date(Date.now() - 360000).toISOString(),
    severity: 'WARNING',
    status: 'ACTIVE',
    category: 'SENSOR',
    message: 'Pressure build-up on Crude Feed Line (842.1 kPa) exceeding safe operating envelope',
    location: 'Sector A - Main Feed Pipe',
    sensorId: 'sns-pres-02',
  },
  {
    id: 'alt-1027',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    severity: 'CRITICAL',
    status: 'ACKNOWLEDGED',
    category: 'EQUIPMENT',
    message: 'Furnace F-101 Exhaust Temperature exceeding extreme structural limits (624.8°C)',
    location: 'Sector B - Primary Furnace',
    sensorId: 'sns-temp-05',
    acknowledgedAt: new Date(Date.now() - 300000).toISOString(),
    assignedTo: 'usr-9428',
  },
  {
    id: 'alt-1026',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    severity: 'DANGER',
    status: 'RESOLVED',
    category: 'SAFETY',
    message: 'Unauthorized technician access detected in Confined Space C-3',
    location: 'Sector D - Storage Terminal',
    resolvedAt: new Date(Date.now() - 1800000).toISOString(),
  },
];

export const MOCK_WORKERS: Worker[] = [
  {
    id: 'wrk-01',
    name: 'Marcus Brody',
    status: 'ACTIVE',
    role: 'Lead Maintenance Tech',
    location: 'Sector A - Hydrocracker',
    heartRate: 74,
    oxygenLevel: 99,
    bodyTemperature: 36.8,
    lastActive: new Date().toISOString(),
    assignedTasks: ['Reactor Valve Recalibration'],
  },
  {
    id: 'wrk-02',
    name: 'Elena Rostova',
    status: 'HAZARD_ALERT',
    role: 'Field Operator',
    location: 'Sector C - Sulfur Recovery',
    heartRate: 114,
    oxygenLevel: 94,
    bodyTemperature: 37.5,
    lastActive: new Date().toISOString(),
    assignedTasks: ['Leak Path Localization'],
  },
  {
    id: 'wrk-03',
    name: 'Darnell Carter',
    status: 'ON_BREAK',
    role: 'Instrument Technician',
    location: 'Control Room 01',
    heartRate: 68,
    oxygenLevel: 99,
    bodyTemperature: 36.6,
    lastActive: new Date(Date.now() - 600000).toISOString(),
    assignedTasks: [],
  },
  {
    id: 'wrk-04',
    name: 'Satoshi Tanaka',
    status: 'ACTIVE',
    role: 'Electrical Supervisor',
    location: 'Sector B - Compressor Deck',
    heartRate: 82,
    oxygenLevel: 98,
    bodyTemperature: 37.1,
    lastActive: new Date().toISOString(),
    assignedTasks: ['Pump P-203 Lockout Tagout Verification'],
  },
];

export const MOCK_PERMITS: WorkPermit[] = [
  {
    id: 'pmt-3011',
    permitNumber: 'WP-2026-9042',
    title: 'Reactor R-02 Catalyst Replacements',
    type: 'CONFINED_SPACE',
    status: 'ACTIVE',
    description: 'Manual catalyst dumping and fresh load replacement inside vessel R-02 dome.',
    location: 'Sector A - Hydrocracker',
    applicant: 'Marcus Brody',
    approver: 'Devin Vance',
    validFrom: new Date(Date.now() - 14400000).toISOString(),
    validTo: new Date(Date.now() + 14400000).toISOString(),
    safetyPrecautions: [
      'Continuous H2S/LEL monitoring',
      'SCBA required for entries',
      'Mechanical ventilation active',
      'Rescue watch stationed at hatchway',
    ],
    hazardsIdentified: ['Oxygen deficiency', 'Toxic gases', 'Pyrophoric material ignition', 'Entrapment'],
  },
  {
    id: 'pmt-3012',
    permitNumber: 'WP-2026-9043',
    title: 'Furnace F-101 Weld Structural Crack Fixes',
    type: 'HOT_WORK',
    status: 'APPROVED',
    description: 'TIG welding repair on outer jacket scaffolding cracks.',
    location: 'Sector B - Primary Furnace',
    applicant: 'Satoshi Tanaka',
    approver: 'Devin Vance',
    validFrom: new Date(Date.now() + 3600000).toISOString(),
    validTo: new Date(Date.now() + 18000000).toISOString(),
    safetyPrecautions: [
      'Gas test 15 mins prior to striking arc',
      'Fire watch positioned with 2x dry chem extinguishers',
      'Shielding blankets on pipes',
    ],
    hazardsIdentified: ['Sparks/slag generation', 'Fumes', 'High surface temperature'],
  },
  {
    id: 'pmt-3013',
    permitNumber: 'WP-2026-9044',
    title: 'High-Voltage Switchgear Calibrations',
    type: 'ELECTRICAL',
    status: 'PENDING',
    description: 'Routine insulation breakdown test and breaker relay calibrations.',
    location: 'Sector B - Substation 02',
    applicant: 'Satoshi Tanaka',
    validFrom: new Date(Date.now() + 7200000).toISOString(),
    validTo: new Date(Date.now() + 14400000).toISOString(),
    safetyPrecautions: ['LOTO locks verified', 'Dielectric mats in place', 'Personal voltage indicator test'],
    hazardsIdentified: ['Arc flash', 'Fatal electrocution', 'Residual stored charge'],
  },
];

export const MOCK_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'not-01',
    timestamp: new Date(Date.now() - 30000).toISOString(),
    title: 'Emergency Alarm Active',
    message: 'Gas leak detected at Sector C (Sulfur Recovery). H2S levels at 12.8 ppm.',
    read: false,
    category: 'ALERT',
  },
  {
    id: 'not-02',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    title: 'Permit WP-2026-9042 Active',
    message: 'Marcus Brody checked in under Confined Space Entry permit.',
    read: false,
    category: 'PERMIT',
  },
  {
    id: 'not-03',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    title: 'System Calibration Routine Complete',
    message: 'Vibration analyzers on Sector B compressors report calibration success.',
    read: true,
    category: 'SYSTEM',
  },
];

export const MOCK_COPILOT_MESSAGES: CopilotMessage[] = [
  {
    id: 'msg-01',
    sender: 'USER',
    content: 'Are there any active safety hazards in Sector C right now?',
    timestamp: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'msg-02',
    sender: 'AI',
    content: 'Yes. Sensor **Gas Detector H2S Point 04** is reporting a toxic gas concentration of **12.8 ppm**, which exceeds the safe threshold of **10.0 ppm**. An active **CRITICAL Alert (alt-1029)** has been raised, and Field Operator **Elena Rostova** is currently dispatched to the sector for leak localization. Standard Operating Procedure SOP-774 dictates SCBA use and continuous ventilation.',
    timestamp: new Date(Date.now() - 580000).toISOString(),
    references: [
      { type: 'SENSOR', id: 'sns-gas-03', name: 'H2S Detector Point 04' },
      { type: 'ALERT', id: 'alt-1029', name: 'Critical Gas Release' },
    ],
  },
];

export const MOCK_KNOWLEDGE_GRAPH = {
  nodes: [
    { id: 'node-reactor', label: 'Reactor R-02', type: 'VESSEL', status: 'OPERATIONAL' },
    { id: 'node-feedline', label: 'Feed Line FL-4', type: 'PIPE', status: 'CRITICAL' },
    { id: 'node-valve', label: 'Safety Valve SV-12', type: 'VALVE', status: 'MAINTENANCE' },
    { id: 'node-compressor', label: 'Compressor C-104', type: 'VESSEL', status: 'OPERATIONAL' },
    { id: 'node-pump', label: 'Aux Pump P-203', type: 'PUMP', status: 'OFFLINE' },
  ],
  links: [
    { source: 'node-reactor', target: 'node-feedline', relation: 'FED_BY' },
    { source: 'node-feedline', target: 'node-valve', relation: 'CONTROLLED_BY' },
    { source: 'node-reactor', target: 'node-compressor', relation: 'PRESSURE_VENTED_TO' },
    { source: 'node-pump', target: 'node-reactor', relation: 'COOLS' },
  ],
};
