export const PERMISSIONS = {
  // Sensor and Telemetry Permissions
  READ_SENSORS: 'sensors:read',
  WRITE_SENSORS: 'sensors:write',
  CALIBRATE_SENSORS: 'sensors:calibrate',

  // Work Permit Permissions
  CREATE_PERMIT: 'permits:create',
  APPROVE_PERMIT: 'permits:approve',
  REVOKE_PERMIT: 'permits:revoke',

  // Worker Management
  READ_WORKERS: 'workers:read',
  TRACK_WORKERS: 'workers:track',

  // Emergency Actions
  TRIGGER_EMERGENCY: 'emergency:trigger',
  CLEAR_EMERGENCY: 'emergency:clear',

  // System Administration
  MANAGE_SETTINGS: 'system:settings',
  VIEW_AUDIT_LOG: 'system:audit_log',
} as const;

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  SYSTEM_ADMIN: Object.values(PERMISSIONS),
  SAFETY_SUPERVISOR: [
    PERMISSIONS.READ_SENSORS,
    PERMISSIONS.CREATE_PERMIT,
    PERMISSIONS.APPROVE_PERMIT,
    PERMISSIONS.REVOKE_PERMIT,
    PERMISSIONS.READ_WORKERS,
    PERMISSIONS.TRACK_WORKERS,
    PERMISSIONS.TRIGGER_EMERGENCY,
    PERMISSIONS.CLEAR_EMERGENCY,
    PERMISSIONS.VIEW_AUDIT_LOG,
  ],
  PLANT_OPERATOR: [
    PERMISSIONS.READ_SENSORS,
    PERMISSIONS.WRITE_SENSORS,
    PERMISSIONS.CREATE_PERMIT,
    PERMISSIONS.READ_WORKERS,
    PERMISSIONS.TRACK_WORKERS,
    PERMISSIONS.TRIGGER_EMERGENCY,
  ],
  MAINTENANCE_TECH: [
    PERMISSIONS.READ_SENSORS,
    PERMISSIONS.WRITE_SENSORS,
    PERMISSIONS.CALIBRATE_SENSORS,
    PERMISSIONS.CREATE_PERMIT,
  ],
  DISPATCHER: [
    PERMISSIONS.READ_SENSORS,
    PERMISSIONS.READ_WORKERS,
    PERMISSIONS.TRACK_WORKERS,
    PERMISSIONS.TRIGGER_EMERGENCY,
  ],
};
