"""
sensor/domain/models.py — Core domain models for Sensor Intelligence.

These are the foundational data contracts used by every component
in the Sensor Intelligence module: ingestion, anomaly detection,
health tracking, threshold policies, and the SensorAgent.

Design decisions:
  - All models are immutable Pydantic v2 (frozen=True) for thread safety.
  - Timestamps default to UTC ISO-8601 for Kafka/Neo4j compatibility.
  - Quality scores (0.0-1.0) follow the existing confidence conventions.
  - Enums are str-based for JSON serialization consistency.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


# ── Enums ──────────────────────────────────────────────────────────────────────


class SensorHealth(str, Enum):
    """Operational health status of a sensor device.

    State transitions follow a finite state machine:
      HEALTHY → DEGRADED → WARNING → CRITICAL → OFFLINE
      Any state → CALIBRATING (maintenance)
      Any state → HEALTHY (recovery after N clean readings)
    """

    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    OFFLINE = "OFFLINE"
    CALIBRATING = "CALIBRATING"


class AnomalyType(str, Enum):
    """Classification of detected sensor anomalies.

    Each type maps to a specific detection engine:
      THRESHOLD_BREACH   → ThresholdEngine
      STATISTICAL_OUTLIER → StatisticalEngine
      RATE_OF_CHANGE     → RateOfChangeEngine
      PATTERN_DEVIATION  → PatternEngine (stuck, drift, oscillation)
      CORRELATION_BREAK  → CorrelationEngine
      STUCK_VALUE        → PatternEngine
      DRIFT              → PatternEngine
    """

    THRESHOLD_BREACH = "THRESHOLD_BREACH"
    STATISTICAL_OUTLIER = "STATISTICAL_OUTLIER"
    RATE_OF_CHANGE = "RATE_OF_CHANGE"
    PATTERN_DEVIATION = "PATTERN_DEVIATION"
    CORRELATION_BREAK = "CORRELATION_BREAK"
    STUCK_VALUE = "STUCK_VALUE"
    DRIFT = "DRIFT"


class AnomalySeverity(str, Enum):
    """Severity classification for anomalies.

    Maps to downstream actions:
      LOW      → Log only
      MEDIUM   → Dashboard alert
      HIGH     → Supervisor notification + Risk Agent trigger
      CRITICAL → Emergency Agent trigger + immediate escalation
    """

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ThresholdPolicyType(str, Enum):
    """Type of threshold enforcement policy.

    STATIC  — Fixed min/max boundaries from sensor configuration.
    DYNAMIC — Rolling percentile-based adaptive boundaries.
    RATE    — Maximum allowed rate-of-change (Δv/Δt) per second.
    """

    STATIC = "STATIC"
    DYNAMIC = "DYNAMIC"
    RATE = "RATE"


class IngestionSource(str, Enum):
    """Origin of ingested sensor readings."""

    REST = "REST"
    KAFKA = "KAFKA"
    BATCH = "BATCH"


# ── Core Reading Model ─────────────────────────────────────────────────────────


class SensorReading(BaseModel):
    """A single telemetry reading from an industrial sensor.

    This is the atomic unit of data flowing through the entire
    Sensor Intelligence pipeline. Every downstream component
    operates on SensorReading instances.

    Attributes:
        reading_id:    Unique identifier for deduplication.
        sensor_id:     Reference to the Sensor node in the Knowledge Graph.
        value:         Raw numeric measurement from the sensor.
        unit:          Engineering unit (e.g. "C", "bar", "ppm", "mm/s").
        timestamp:     UTC ISO-8601 when the reading was captured.
        quality_score: Data quality indicator (0.0=garbage, 1.0=pristine).
        metadata:      Extensible key-value pairs (calibration offset, firmware, etc).
    """

    model_config = ConfigDict(frozen=True)

    reading_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sensor_id: str = Field(..., description="Knowledge Graph Sensor node ID")
    value: float = Field(..., description="Raw numeric measurement")
    unit: str = Field(default="", description="Engineering unit")
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat(),
        description="UTC ISO-8601 capture timestamp",
    )
    quality_score: float = Field(
        default=1.0, ge=0.0, le=1.0, description="Data quality (0.0-1.0)"
    )
    metadata: dict[str, Any] = Field(default_factory=dict)


# ── Anomaly Model ─────────────────────────────────────────────────────────────


class SensorAnomaly(BaseModel):
    """A detected anomaly on a sensor reading.

    Generated by one of the five anomaly detection engines.
    Multiple anomalies can be produced from a single reading
    if multiple engines flag it simultaneously.

    Attributes:
        anomaly_id:      Unique identifier for tracking.
        sensor_id:       Which sensor produced the anomalous reading.
        anomaly_type:    Which engine detected this (maps to AnomalyType).
        severity:        Downstream action severity.
        value:           The anomalous reading value.
        expected_value:  What the engine expected (mean, threshold, etc).
        threshold:       The boundary that was violated.
        deviation_sigma: Standard deviations from expected (statistical engine).
        description:     Human-readable explanation.
        timestamp:       When the anomaly was detected.
        engine_name:     Name of the detection engine that flagged this.
    """

    model_config = ConfigDict(frozen=True)

    anomaly_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sensor_id: str
    anomaly_type: AnomalyType
    severity: AnomalySeverity
    value: float
    expected_value: float | None = None
    threshold: float | None = None
    deviation_sigma: float | None = None
    description: str = ""
    timestamp: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    engine_name: str = ""


# ── Health State Model ─────────────────────────────────────────────────────────


class SensorHealthState(BaseModel):
    """Operational health state of a sensor device.

    Maintained by the SensorHealthTracker. Updated on every reading.
    Tracks rolling statistics for baseline comparison.

    Attributes:
        sensor_id:               Knowledge Graph Sensor node ID.
        status:                  Current health status (FSM state).
        consecutive_anomalies:   Number of consecutive anomalous readings.
        consecutive_healthy:     Number of consecutive clean readings (for recovery).
        last_healthy_reading:    Timestamp of last reading with no anomalies.
        last_reading_timestamp:  Timestamp of most recent reading (any status).
        uptime_pct:              Rolling uptime percentage (0.0-100.0).
        total_readings:          Total readings processed for this sensor.
        total_anomalies:         Total anomalies detected for this sensor.
        mean_reading:            Rolling mean of recent readings.
        std_reading:             Rolling std deviation of recent readings.
    """

    sensor_id: str
    status: SensorHealth = SensorHealth.HEALTHY
    consecutive_anomalies: int = 0
    consecutive_healthy: int = 0
    last_healthy_reading: str | None = None
    last_reading_timestamp: str | None = None
    uptime_pct: float = 100.0
    total_readings: int = 0
    total_anomalies: int = 0
    mean_reading: float = 0.0
    std_reading: float = 0.0


# ── Threshold Policy Model ────────────────────────────────────────────────────


class ThresholdPolicy(BaseModel):
    """A threshold enforcement policy for a sensor.

    Supports three modes:
      STATIC  — Fixed min/max from sensor config or manual override.
      DYNAMIC — Rolling percentile-based adaptive thresholds.
      RATE    — Maximum Δv/Δt rate limit.

    Attributes:
        policy_id:         Unique policy identifier.
        sensor_id:         Which sensor this policy applies to.
        policy_type:       STATIC, DYNAMIC, or RATE.
        min_value:         Lower bound (STATIC/DYNAMIC).
        max_value:         Upper bound (STATIC/DYNAMIC).
        rate_limit_per_sec: Maximum allowed Δv/Δt (RATE only).
        window_size:       Number of readings for rolling calculations.
        cooldown_sec:      Minimum seconds between consecutive alerts.
        percentile_lower:  Lower percentile for DYNAMIC mode (e.g. 5.0).
        percentile_upper:  Upper percentile for DYNAMIC mode (e.g. 95.0).
        enabled:           Whether this policy is actively enforced.
    """

    model_config = ConfigDict(frozen=True)

    policy_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    sensor_id: str
    policy_type: ThresholdPolicyType = ThresholdPolicyType.STATIC
    min_value: float | None = None
    max_value: float | None = None
    rate_limit_per_sec: float | None = None
    window_size: int = Field(default=100, ge=10, le=10000)
    cooldown_sec: float = Field(default=60.0, ge=0.0)
    percentile_lower: float = Field(default=5.0, ge=0.0, le=50.0)
    percentile_upper: float = Field(default=95.0, ge=50.0, le=100.0)
    enabled: bool = True


# ── Ingestion Batch Model ──────────────────────────────────────────────────────


class IngestionBatch(BaseModel):
    """A batch of sensor readings submitted for ingestion.

    Attributes:
        batch_id:    Unique batch identifier for tracking.
        readings:    List of sensor readings in this batch.
        received_at: UTC ISO-8601 when the batch arrived at the gateway.
        source:      Origin of the batch (REST, KAFKA, BATCH).
    """

    model_config = ConfigDict(frozen=True)

    batch_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    readings: list[SensorReading] = Field(default_factory=list)
    received_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    source: IngestionSource = IngestionSource.REST
