from __future__ import annotations
from enum import Enum

class ModelStage(str, Enum):
    DRAFT = "DRAFT"
    REVIEW = "REVIEW"
    STAGING = "STAGING"
    PRODUCTION = "PRODUCTION"
    RETIRED = "RETIRED"
    ARCHIVED = "ARCHIVED"

class ModelStatus(str, Enum):
    TRAINING = "TRAINING"
    TRAINED = "TRAINED"
    EVALUATING = "EVALUATING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEPLOYED = "DEPLOYED"
    FAILED = "FAILED"
    DEPRECATED = "DEPRECATED"

class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    REVOKED = "REVOKED"

class DriftType(str, Enum):
    DATA = "DATA"
    CONCEPT = "CONCEPT"
    PREDICTION = "PREDICTION"
    FEATURE = "FEATURE"
    PERFORMANCE = "PERFORMANCE"

class DriftSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class FeatureType(str, Enum):
    NUMERICAL = "NUMERICAL"
    CATEGORICAL = "CATEGORICAL"
    BOOLEAN = "BOOLEAN"
    TEXT = "TEXT"
    EMBEDDING = "EMBEDDING"
    TIMESTAMP = "TIMESTAMP"
    BINARY = "BINARY"

class TenantTier(str, Enum):
    COMMUNITY = "COMMUNITY"
    PROFESSIONAL = "PROFESSIONAL"
    ENTERPRISE = "ENTERPRISE"
    GOVERNMENT = "GOVERNMENT"

class PlantStatus(str, Enum):
    ACTIVE = "ACTIVE"
    MAINTENANCE = "MAINTENANCE"
    OFFLINE = "OFFLINE"
    DECOMMISSIONED = "DECOMMISSIONED"

class GovernancePolicy(str, Enum):
    FAIRNESS = "FAIRNESS"
    TRANSPARENCY = "TRANSPARENCY"
    ACCOUNTABILITY = "ACCOUNTABILITY"
    PRIVACY = "PRIVACY"
    SAFETY = "SAFETY"
    ROBUSTNESS = "ROBUSTNESS"

class DeploymentStrategy(str, Enum):
    ROLLING = "ROLLING"
    BLUE_GREEN = "BLUE_GREEN"
    CANARY = "CANARY"
    RECREATE = "RECREATE"

class AlertSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"

class HealthStatus(str, Enum):
    HEALTHY = "HEALTHY"
    DEGRADED = "DEGRADED"
    UNHEALTHY = "UNHEALTHY"
    UNKNOWN = "UNKNOWN"

class LicenseTier(str, Enum):
    COMMUNITY = "COMMUNITY"
    PROFESSIONAL = "PROFESSIONAL"
    ENTERPRISE = "ENTERPRISE"
    UNLIMITED = "UNLIMITED"

class AuditAction(str, Enum):
    MODEL_REGISTERED = "MODEL_REGISTERED"
    MODEL_PROMOTED = "MODEL_PROMOTED"
    MODEL_REJECTED = "MODEL_REJECTED"
    MODEL_RETIRED = "MODEL_RETIRED"
    TENANT_CREATED = "TENANT_CREATED"
    TENANT_SUSPENDED = "TENANT_SUSPENDED"
    API_KEY_CREATED = "API_KEY_CREATED"
    API_KEY_REVOKED = "API_KEY_REVOKED"
    POLICY_UPDATED = "POLICY_UPDATED"
    DRIFT_ALERT = "DRIFT_ALERT"
    RETRAINING_TRIGGERED = "RETRAINING_TRIGGERED"
    GOVERNANCE_DECISION = "GOVERNANCE_DECISION"
    SECURITY_EVENT = "SECURITY_EVENT"

class RetrainingTrigger(str, Enum):
    SCHEDULED = "SCHEDULED"
    DRIFT_DETECTED = "DRIFT_DETECTED"
    PERFORMANCE_DROP = "PERFORMANCE_DROP"
    FEEDBACK_THRESHOLD = "FEEDBACK_THRESHOLD"
    MANUAL = "MANUAL"

class OnlineLearningStatus(str, Enum):
    IDLE = "IDLE"
    INGESTING = "INGESTING"
    UPDATING = "UPDATING"
    RETRAINING = "RETRAINING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
