"""
domain/entities/vision_assessment.py — Strongly Typed Supervisor Contract Payloads.

Defines VisionAssessment, VisionRecommendation, VisionIncidentCandidate,
and VisionEmergencyCandidate to avoid loose dictionaries when sending
evaluations to the Supervisor Agent.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any

from pydantic import BaseModel, Field

from app.modules.vision.domain.entities.vision_evidence import VisionEvidence


class VisionRecommendation(BaseModel):
    """Actionable recommendation generated by Vision AI."""

    recommendation_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str
    target_role: str = "Safety Officer"
    priority: str = "HIGH"  # LOW | MEDIUM | HIGH | CRITICAL
    action_type: str = "DISPATCH_INSPECTION"
    policy_reference: str | None = None
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class VisionIncidentCandidate(BaseModel):
    """Candidate incident report compiled from Vision Intelligence."""

    candidate_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    severity: str = "HIGH"
    zone_id: str
    camera_id: str
    hazard_type: str
    summary: str
    suggested_root_cause: str | None = None


class VisionEmergencyCandidate(BaseModel):
    """Emergency trigger compiled from Critical Vision Events (Fall / Fire / Crane Threat)."""

    emergency_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    emergency_type: str  # FALL_MEDICAL_EMERGENCY | CONFIRMED_FIRE | CRITICAL_ZONE_BREACH
    zone_id: str
    plant_id: str | None = None
    severity: str = "CRITICAL"
    trigger_reason: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())


class VisionAssessment(BaseModel):
    """
    Unified, strongly typed payload sent from Vision Intelligence to Supervisor Agent.
    """

    assessment_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    camera_id: str
    zone_id: str | None = None
    plant_id: str | None = None
    assessment_type: str  # PPE | BEHAVIOR | ZONE | INTERACTION | FALL | FIRE | OCCUPANCY
    overall_risk_score: float = Field(..., ge=0.0, le=100.0)
    risk_level: str = "LOW"  # LOW | MEDIUM | HIGH | CRITICAL

    evidence: VisionEvidence
    recommendations: list[VisionRecommendation] = Field(default_factory=list)

    # Optional Escalations
    incident_candidate: VisionIncidentCandidate | None = None
    emergency_candidate: VisionEmergencyCandidate | None = None

    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
